version: '3'
networks:
  my_app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
services:
  my-app-api:
    build:
      context: ./my-app-api
    ports: 
      - 3030:3030
    networks:
      - my_app_network
  my-app-front:
    build:
      context: ./my-app-front
    ports:
      - 3000:3000
    networks:
      - my_app_network
    environment:
      - NEXT_PUBLIC_API_ENDPOINT="http://127.0.0.1:3030/api"
      - NEXT_PUBLIC_BACKEND_URL="http://127.0.0.1:3030"
    depends_on:
      - my-app-api