version: '3'
networks:
  my_app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
services:
  my-store-api:
    env_file:
      - ../my-store-api/.env
    build:
      context: ../my-store-api
    ports: 
      - 3030:3030
    networks:
      - my_app_network
  my-store-front:
    env_file:
      - ../my-store-front/.env
    build:
      context: ../my-store-front
    ports:
      - 3000:3000
    networks:
      - my_app_network
    depends_on:
      - my-store-api