version: '3'
networks:
  my_app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
services:
  my-store-api:
    build:
      context: ../my-store-api
    ports: 
      - 3030:3030
    networks:
      - my_app_network
  my-store-front:
    build:
      context: ../my-store-front
    ports:
      - 3000:3000
    networks:
      - my_app_network
    environment:
      - NEXT_PUBLIC_API_ENDPOINT="http://my-store-api:3030/api"
      - NEXT_PUBLIC_BACKEND_URL="http://my-store-api:3030"
    depends_on:
      - my-store-api
    command: ["./wait-for-it.sh", "my-store-api", "3030", "--", "npm", "start"]